model_name: clip_roberta_adaptor_clf
general:
  seed: 42
  wandb: False
  ddp: False
  ncpus: 8
  gpus: 0
  world_size: 4
  rank: 0
  device: "cuda"
  preprocess: False
  load_trained_model_for_testing: False 

dataset:
  path_to_data: "/data/gauravs/combine_data"
  shuffle: True
  vocab_freq: 5
  sample_size: 25000
  num_workers: 0
  pin_memory: False
  labels: ["Abdominal_wall_cavity", "liver", "cystic_plate", "red", "brown", 
          "silver", "instrument", "anatomy", "grasper", "gallbladder", "omentum", 
          "white", "yellow", "gut", "hook"]

training:
  general:
    clip: 1 
    batch_size: 20
    epochs: 50
    dropout: 0.3
    learning_rate: 0.0001
    weight_decay: 0.00001
    betas: [0.9,0.8]
    early_stopping: 7
  
  scheduler:
    isScheduler: True
    verbose: True
    scheduler_step_size: 5
    scheduler_gamma: 0.9
  
  adaptor:
    features: [512,256,128,64]

  roberta:
    in_dim: 768
    finetune: False

  clip:
    finetune: False
    configuration: 
      hidden_size: 128
      intermediate_size: 1408
      projection_dim: 192
      num_hidden_layers: 3
      num_attention_heads: 4
      num_channels: 3
      image_size: 224
      patch_size: 32
  
  bilstm:
    in_dim: 64
    hidden_dim: 64
    embed_dim: 64